[package]
name = "petit-cadeau"
version = "1.1.0"
authors = ["dpapin1118 <denis.pro@isd.lu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rand = "0.7.3"
